# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-30 14:16
from __future__ import unicode_literals

import apps.noticia.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=35000, null=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('cierre', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.ImageField(help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 740x480 pixeles', upload_to='noticias/', validators=[apps.noticia.models.validate_image_noticia])),
                ('mostrar', models.BooleanField(default=True, help_text='Visualizar noticia.')),
            ],
            options={
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
