# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-19 14:31
from __future__ import unicode_literals

import apps.documentos.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000, null=True)),
                ('archivo', models.FileField(help_text='Tamaño máximo del archivo es 15Mb y solo se permite .pdf .docx .xlsx.', max_length=20000, upload_to='documentos/', validators=[apps.documentos.models.validate_document])),
                ('mostrar', models.BooleanField(default=True, help_text='Visualizar este Documento.')),
                ('prioridad', models.IntegerField(default=1, help_text='Prioridad en el que se publican estos contenidos.')),
            ],
        ),
    ]
