# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-06 21:18
from __future__ import unicode_literals

import apps.documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=5000, null=True)),
                ('tipo_documento', models.CharField(choices=[(b'G', b'Documento General'), (b'A', b'Documento Actividades Vinculac\xc3\xadon'), (b'I', b'Documento Investigaci\xc3\xb3n'), (b'P', b'Documento Pol\xc3\xadticas Vinculaci\xc3\xb3n')], default=b'G', max_length=100)),
                ('archivo', models.FileField(help_text=b'Tama\xc3\xb1o m\xc3\xa1ximo del archivo es 15Mb y solo se permite .pdf .docx .xlsx.', max_length=5000, upload_to=b'documentos/', validators=[apps.documentos.models.validate_document])),
                ('mostrar', models.BooleanField(default=True, help_text=b'Visualizar este Documento.')),
                ('prioridad', models.IntegerField(default=1, help_text=b'Prioridad en el que se publican estos contenidos.')),
            ],
        ),
    ]
