# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-19 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
