# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-30 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20201019_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('G', 'Documento General'), ('A', 'Documento Actividades Vinculacíon'), ('I', 'Documento Investigación'), ('P', 'Documento Políticas Vinculación')], default='G', max_length=1),
        ),
    ]
