# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-28 20:44
from __future__ import unicode_literals

import apps.actividad.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=35000, null=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('cierre', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.ImageField(help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 420x420 pixeles', upload_to='calendario/', validators=[apps.actividad.models.validate_image_actividad])),
                ('mostrar', models.BooleanField(default=True, help_text='Visualizar actividad.')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
