# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-30 12:20
from __future__ import unicode_literals

import apps.actividad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_auto_20201028_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='imagen',
            field=models.ImageField(help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 740x480 pixeles', upload_to='actividad/', validators=[apps.actividad.models.validate_image_actividad]),
        ),
    ]
