# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-10 13:53
from __future__ import unicode_literals

import apps.investigacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', apps.investigacion.models.IntegerRangeField(default=2020, verbose_name='A\xf1o')),
                ('produccion_investigacion', apps.investigacion.models.IntegerRangeField(default=0, verbose_name='N\xb0 de actividades o publicaciones asociadas a investigaci\xf3n')),
                ('produccion_educacional', apps.investigacion.models.IntegerRangeField(default=0, verbose_name='N\xb0 de actividades o publicaciones asociadas a educaci\xf3n')),
            ],
            options={
                'ordering': ['temporada'],
                'verbose_name_plural': 'Cantidad de trabajos por a\xf1o',
            },
        ),
    ]
