# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-09-01 13:17
from __future__ import unicode_literals

import apps.investigacion.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productividad',
            name='temporada',
            field=apps.investigacion.models.IntegerRangeField(default=2024, verbose_name='A\xf1o'),
        ),
    ]
