# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-09 01:53
from __future__ import unicode_literals

import apps.equipo_directivo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('tipo_cargo', models.CharField(choices=[('D', 'Direcci\xf3n'), ('A', 'Administraci\xf3n'), ('C', 'Coordinaci\xf3n')], default='G', max_length=1)),
                ('foto', models.ImageField(help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 270x270 pixeles', upload_to='equipo_directivo/directivos/', validators=[apps.equipo_directivo.models.validate_image_docente])),
                ('nivel', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['nivel'],
                'verbose_name_plural': 'Directivos',
            },
        ),
    ]
