# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 13:49
from __future__ import unicode_literals

import apps.clinica.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=300)),
                ('foto', models.ImageField(help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 120x120 pixeles', upload_to='equipo/', validators=[apps.clinica.models.validate_image])),
                ('nivel', models.IntegerField(default=1)),
                ('tipo_equipo', models.CharField(choices=[('funcionario', 'Funcionario'), ('academico', 'Acad\xe9mico')], max_length=10)),
            ],
            options={
                'ordering': ['nivel'],
            },
        ),
    ]
