# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 19:58
from __future__ import unicode_literals

import apps.clinica.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('director', 'Director T\xe9cnico'), ('enfermera', 'Enfermera Coordinadora'), ('tecnico', 'T\xe9cnico Dental'), ('secretaria', 'Secretaria Administrativa'), ('auxiliar', 'Auxiliar de Servicio')], max_length=10)),
                ('foto', models.ImageField(help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 120x120 pixeles', upload_to='clinica/equipo/', validators=[apps.clinica.models.validate_image])),
                ('nivel', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('valor', models.IntegerField()),
                ('tipo_servicio', models.CharField(choices=[('imagenologia ', 'Imagenolog\xeda'), ('odontologia', 'Odontolog\xeda')], max_length=13)),
            ],
        ),
    ]
