# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 20:11
from __future__ import unicode_literals

import apps.clinica.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(help_text='Tamano maximo de la imagen es de 1Mb y sus dimensiones deben ser de 1200x800px', upload_to='clinica/galeria/', validators=[apps.clinica.models.validate_image_galeria])),
                ('nivel', models.IntegerField(default=1)),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Galeria')),
            ],
            options={
                'verbose_name_plural': 'imagenes',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', models.ImageField(help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 426x582 pixeles', upload_to='clinica/servicio/', validators=[apps.clinica.models.validate_image_servicio])),
                ('descripcion', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='valor',
        ),
        migrations.AlterField(
            model_name='contenido',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=35000, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='foto',
            field=models.ImageField(help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 270x270 pixeles', upload_to='clinica/equipo/', validators=[apps.clinica.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.TipoServicio'),
        ),
    ]
