# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-09-01 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='cargo',
            field=models.CharField(choices=[('director', 'Director T\xe9cnico'), ('admin_coa', 'administradora COAD'), ('radiologa', 'Radi\xf3loga Coordinadora'), ('enf_coord', 'Enfermera Coordinadora'), ('enfermera', 'Enfermera'), ('tecnico', 'T\xe9cnico Dental'), ('secretaria', 'Secretaria Administrativa'), ('auxiliar', 'Auxiliar de Servicio'), ('mayordomo', 'Mayordomo'), ('tec_mante', 'T\xe9cnico en Mantenci\xf3n'), ('guardia', 'Guardia')], max_length=10),
        ),
    ]
