# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 02:12
from __future__ import unicode_literals

import apps.clinica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='foto',
            field=models.ImageField(help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 270x270 pixeles', upload_to='clinica/equipo/', validators=[apps.clinica.models.validate_image]),
        ),
    ]
