# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-09 02:47
from __future__ import unicode_literals

import apps.carrera.models
import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCientificoProductivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', ckeditor_uploader.fields.RichTextUploadingField(max_length=300)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True)),
                ('anio', models.CharField(blank=True, max_length=30, null=True, verbose_name='A\xf1o')),
                ('orden', models.IntegerField(default=1, help_text='Orden que se desplegar\xe1 la actividad')),
                ('mostrar', models.BooleanField(default=True, help_text='Mostrar u ocultar la actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadGruposInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', ckeditor_uploader.fields.RichTextUploadingField(max_length=300)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True)),
                ('objetivo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True)),
                ('anio', models.CharField(blank=True, max_length=30, null=True, verbose_name='A\xf1o')),
                ('grupo_interes', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=1, help_text='Orden que se desplegar\xe1 la actividad')),
                ('mostrar', models.BooleanField(default=True, help_text='Mostrar u ocultar la actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadNumeroBeneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=10, verbose_name='A\xf1o')),
                ('beneficiario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadPoliticaPublica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', ckeditor_uploader.fields.RichTextUploadingField(max_length=300)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True)),
                ('participantes', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=300, null=True)),
                ('anio', models.CharField(blank=True, max_length=30, null=True, verbose_name='A\xf1o')),
                ('grupo_interes', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=1, help_text='Orden que se desplegar\xe1 la actividad')),
                ('mostrar', models.BooleanField(default=True, help_text='Mostrar u ocultar la actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadPoliticaPublicaParticipacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=20)),
                ('institucion_externa', models.CharField(max_length=100)),
                ('objetivo_reunion', ckeditor_uploader.fields.RichTextUploadingField(max_length=300)),
                ('tipo_participacion', ckeditor_uploader.fields.RichTextUploadingField(max_length=300)),
                ('orden', models.IntegerField(default=1, help_text='Orden que se desplegar\xe1 la actividad')),
                ('mostrar', models.BooleanField(default=True, help_text='Mostrar u ocultar la actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Admision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='a\xf1o')),
                ('puntaje_minimo', models.FloatField(verbose_name='puntaje m\xednimo')),
                ('puntaje_maximo', models.FloatField(verbose_name='puntaje m\xe1ximo')),
                ('puntaje_ponderado', models.FloatField(verbose_name='puntaje ponderado')),
                ('vacantes', models.PositiveSmallIntegerField(verbose_name='Vacantes')),
            ],
            options={
                'ordering': ['anio'],
                'verbose_name_plural': 'Admisiones',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=8)),
                ('mensaje', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
                ('fecha_contacto', models.DateTimeField()),
                ('contacto_destino', models.CharField(choices=[('carrera', 'Carrera'), ('clinica', 'Cl\xednica')], max_length=11)),
            ],
            options={
                'ordering': ['fecha_contacto'],
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=35000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('cargo', ckeditor.fields.RichTextField(max_length=500, null=True)),
                ('titulo', models.CharField(max_length=150)),
                ('area', models.CharField(choices=[('rehabilitacion_oral', 'Rehabilitaci\xf3n Oral'), ('odontopediatria', 'Odontopediatr\xeda'), ('periodoncia', 'Periodoncia'), ('endodoncia', 'Endodoncia'), ('cirugia', 'Cirug\xeda'), ('ciencias_preclinicas', 'Ciencias Precl\xednicas')], max_length=30)),
                ('especialidad', ckeditor.fields.RichTextField(max_length=500, null=True)),
                ('postitulos', ckeditor.fields.RichTextField(max_length=500, null=True)),
                ('registro_siss', models.CharField(default=0, max_length=100)),
                ('foto', models.ImageField(help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 270x270 pixeles', upload_to='carrera/docente/', validators=[apps.carrera.models.validate_image_docente])),
                ('nivel', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['nivel'],
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='TipoPoliticaPublica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=400)),
                ('orden', models.IntegerField(default=1, help_text='Orden que se desplegar\xe1 tipo politica publica')),
                ('mostrar', models.BooleanField(default=True, help_text='Mostrar u ocultar el tipo')),
            ],
        ),
        migrations.AddField(
            model_name='actividadpoliticapublica',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrera.TipoPoliticaPublica'),
        ),
    ]
