# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-28 20:04
from __future__ import unicode_literals

import apps.carrera.models
import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=35000, null=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('cierre', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.ImageField(help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 420x420 pixeles', upload_to='calendario/', validators=[apps.carrera.models.validate_image_actividad])),
                ('mostrar', models.BooleanField(default=True, help_text='Visualizar actividad.')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Admision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('puntaje_minimo', models.FloatField(verbose_name='puntaje mínimo')),
                ('puntaje_maximo', models.FloatField(verbose_name='puntaje máximo')),
                ('puntaje_ponderado', models.FloatField(verbose_name='puntaje ponderado')),
                ('vacantes', models.PositiveSmallIntegerField(verbose_name='Vacantes')),
            ],
            options={
                'verbose_name_plural': 'Admisiones',
                'ordering': ['anio'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=8)),
                ('mensaje', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
                ('fecha_contacto', models.DateTimeField()),
                ('contacto_destino', models.CharField(choices=[('carrera', 'Carrera'), ('clinica', 'Clínica')], max_length=11)),
            ],
            options={
                'ordering': ['fecha_contacto'],
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=35000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('cargo', ckeditor.fields.RichTextField(max_length=500, null=True)),
                ('titulo', models.CharField(max_length=150)),
                ('area', models.CharField(choices=[('rehabilitacion_oral', 'Rehabilitación Oral'), ('odontopediatria', 'Odontopediatría'), ('periodoncia', 'Periodoncia'), ('endodoncia', 'Endodoncia'), ('cirugia', 'Cirugía'), ('ciencias_preclinicas', 'Ciencias Preclínicas')], max_length=30)),
                ('especialidad', ckeditor.fields.RichTextField(max_length=500, null=True)),
                ('postitulos', ckeditor.fields.RichTextField(max_length=500, null=True)),
                ('registro_siss', models.CharField(default=0, max_length=100)),
                ('foto', models.ImageField(help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 270x270 pixeles', upload_to='carrera/docente/', validators=[apps.carrera.models.validate_image_docente])),
                ('nivel', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Docentes',
                'ordering': ['nivel'],
            },
        ),
    ]
