# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='a\xf1o')),
                ('puntaje_minimo', models.FloatField(verbose_name='puntaje m\xednimo')),
                ('puntaje_maximo', models.FloatField(verbose_name='puntaje m\xe1ximo')),
                ('puntaje_ponderado', models.FloatField(verbose_name='puntaje ponderado')),
                ('vacantes', models.PositiveSmallIntegerField(verbose_name='Vacantes')),
            ],
        ),
    ]
