# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-20 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='casa_estudio',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='docentes',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='area',
            field=models.CharField(choices=[('rehabilitacion_oral', 'Rehabilitaci\xf3n Oral'), ('odontopediatria', 'Odontopediatr\xeda'), ('periodoncia', 'Periodoncia'), ('endodoncia', 'Endodoncia'), ('cirugia', 'Cirug\xeda'), ('ciencias_preclinicas', 'Ciencias B\xe1sicas y Precl\xednicas'), ('ortodoncia_ortopedia', 'Ortodoncia y Ortopedia'), ('radiologia_imagenologia', 'Radiolog\xeda y Imagenolog\xeda')], max_length=30),
        ),
    ]
