# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-06 13:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCientificoProductivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', ckeditor_uploader.fields.RichTextUploadingField(max_length=300)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True)),
                ('anio', models.CharField(blank=True, max_length=30, null=True, verbose_name='Año')),
                ('orden', models.IntegerField(default=1, help_text='Orden que se desplegará la actividad')),
                ('mostrar', models.BooleanField(default=True, help_text='Mostrar u ocultar la actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadGruposInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', ckeditor_uploader.fields.RichTextUploadingField(max_length=300)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True)),
                ('objetivo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True)),
                ('anio', models.CharField(blank=True, max_length=30, null=True, verbose_name='Año')),
                ('grupo_interes', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=1, help_text='Orden que se desplegará la actividad')),
                ('mostrar', models.BooleanField(default=True, help_text='Mostrar u ocultar la actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadPoliticaPublica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', ckeditor_uploader.fields.RichTextUploadingField(max_length=300)),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True)),
                ('participantes', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=300, null=True)),
                ('anio', models.CharField(blank=True, max_length=30, null=True, verbose_name='Año')),
                ('grupo_interes', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=1, help_text='Orden que se desplegará la actividad')),
                ('mostrar', models.BooleanField(default=True, help_text='Mostrar u ocultar la actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadPoliticaPublicaParticipacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=20)),
                ('institucion_externa', models.CharField(max_length=100)),
                ('objetivo_reunion', ckeditor_uploader.fields.RichTextUploadingField(max_length=300)),
                ('tipo_participacion', ckeditor_uploader.fields.RichTextUploadingField(max_length=300)),
                ('orden', models.IntegerField(default=1, help_text='Orden que se desplegará la actividad')),
                ('mostrar', models.BooleanField(default=True, help_text='Mostrar u ocultar la actividad')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPoliticaPublica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=400)),
                ('orden', models.IntegerField(default=1, help_text='Orden que se desplegará tipo politica publica')),
                ('mostrar', models.BooleanField(default=True, help_text='Mostrar u ocultar el tipo')),
            ],
        ),
        migrations.AddField(
            model_name='actividadpoliticapublica',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrera.TipoPoliticaPublica'),
        ),
    ]
