# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-06 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0002_auto_20201106_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadNumeroBeneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=10, verbose_name='Año')),
                ('beneficiario', models.CharField(max_length=30)),
            ],
        ),
    ]
