# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-20 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0002_auto_20201120_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='email',
            field=models.EmailField(default='odontologia@userena.cl', max_length=254),
        ),
    ]
