# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 04:13
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0002_auto_20180115_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=100)),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
