# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 02:12
from __future__ import unicode_literals

import apps.carrera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0004_auto_20180119_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('titulo', models.CharField(choices=[('candidato_doctor', 'C.D.'), ('profesor', 'Profesor'), ('magister', 'M.G')], max_length=10)),
                ('foto', models.ImageField(help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 270x270 pixeles', upload_to='carrera/docente/', validators=[apps.carrera.models.validate_image])),
                ('nivel', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['nivel'],
            },
        ),
    ]
