# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 20:11
from __future__ import unicode_literals

import apps.carrera.models
import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0004_auto_20180119_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=8)),
                ('mensaje', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
                ('fecha_contacto', models.DateTimeField()),
                ('contacto_destino', models.CharField(choices=[('carrera', 'Carrera'), ('clinica', 'Cl\xednica')], max_length=11)),
            ],
            options={
                'ordering': ['fecha_contacto'],
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('titulo', models.CharField(choices=[('candidato_doctor', 'C.D.'), ('profesor', 'Profesor'), ('magister', 'MG.')], max_length=20)),
                ('area', models.CharField(choices=[('docente', 'docente'), ('endodoncia', 'endodoncia'), ('odontopediatria', 'odontopediatria')], max_length=30)),
                ('foto', models.ImageField(help_text='Tamano maximo de la imagen es 1Mb, sus dimensiones deben ser de 270x270 pixeles', upload_to='carrera/docente/', validators=[apps.carrera.models.validate_image])),
                ('nivel', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['nivel'],
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.DeleteModel(
            name='Contactos',
        ),
        migrations.AlterField(
            model_name='contenido',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=35000, null=True),
        ),
    ]
