# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 13:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0005_auto_20180514_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='especialidad',
            field=ckeditor.fields.RichTextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='docentes',
            name='postitulos',
            field=ckeditor.fields.RichTextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='docentes',
            name='registro_siss',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='area',
            field=models.CharField(choices=[('rehabilitacion_oral', 'Rehabilitaci\xf3n Oral'), ('odontopediatria', 'Odontopediatr\xeda'), ('periodoncia', 'Periodoncia'), ('endodoncia', 'Endodoncia'), ('cirugia', 'Cirug\xeda'), ('ciencias_preclinicas', 'Ciencias Precl\xednicas')], max_length=30),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='cargo',
            field=ckeditor.fields.RichTextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
