# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0005_docentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
