# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0006_auto_20180121_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='titulo',
            field=models.CharField(choices=[('candidato_doctor', 'C.D.'), ('profesor', 'Profesor'), ('magister', 'M.G')], max_length=20),
        ),
    ]
