# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 15:41
from __future__ import unicode_literals

import ckeditor_uploader.fields
from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0007_auto_20180121_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactos',
            options={'ordering': ['fecha_contacto']},
        ),
        migrations.AddField(
            model_name='contactos',
            name='fecha_contacto',
            field=models.DateTimeField(default=datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contenido',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10000, null=True),
        ),
    ]
