# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0008_auto_20180122_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='docentes',
            name='area',
            field=models.CharField(choices=[('endodoncia', 'Endodoncia'), ('endodoncista', 'endodoncista'), ('docente', 'docente')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docentes',
            name='titulo',
            field=models.CharField(choices=[('candidato_doctor', 'C.D.'), ('profesor', 'Profesor'), ('magister', 'MG.')], max_length=20),
        ),
    ]
