# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 11:54
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0009_auto_20180123_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=35000, null=True),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='area',
            field=models.CharField(choices=[('docente', 'docente'), ('endodoncia', 'endodoncia'), ('odontopediatria', 'odontopediatria')], max_length=30),
        ),
    ]
